### ISSUE TITLE
metabase_permissions_group panics on create

### ISSUE THREAD

**Issue by iwahbe** [flovouin/terraform-provider-metabase#69]
When attempting to create the `metabase_permissions_group` resource, the provider panics:

```console
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # metabase_permissions_group.example will be created
  + resource "metabase_permissions_group" "example" {
      + id   = (known after apply)
      + name = "example"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

metabase_permissions_group.example: Creating...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-metabase_v0.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104b9b444]

goroutine 37 [running]:
github.com/flovouin/terraform-provider-metabase/internal/provider.(*PermissionsGroupResource).Create(0x14000412e70, {0x1051265a8, 0x14000512330}, {{{{0x10512b3f8, 0x14000512900}, {0x10500afa0, 0x14000512870}}, {0x10512d6c8, 0x1400042a960}}, {{{0x10512b3f8, ...}, ...}, ...}, ...}, ...)
        github.com/flovouin/terraform-provider-metabase/internal/provider/permissions_group_resource.go:81 +0x1f4
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140002821e0, {0x1051265a8, 0x14000512330}, 0x140000c35c8, 0x140000c35a0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x400
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140002821e0, {0x1051265a8, 0x14000512330}, 0x1400042b2c0, 0x140000c36c0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140002821e0, {0x1051265a8?, 0x14000512240?}, 0x1400042b220)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000294aa0, {0x1051265a8?, 0x14000475830?}, 0x14000434f50)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1050f5280, 0x14000294aa0}, {0x1051265a8, 0x14000475830}, 0x14000504380, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000192e00, {0x1051265a8, 0x140004757a0}, {0x10512c380, 0x140000e6000}, 0x1400050a360, 0x1400038c270, 0x105662278, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xb78
google.golang.org/grpc.(*Server).handleStream(0x14000192e00, {0x10512c380, 0x140000e6000}, 0x1400050a360)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 8
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x13c

Error: The terraform-provider-metabase_v0.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

My config file looked like:

```hcl
terraform {
  required_providers {
    metabase = {
      source = "flovouin/metabase"
    }
  }
}

provider "metabase" {
  endpoint = "http://127.0.0.1:3000"

  api_key = "mb_Q5D0iER0AXSS8Zdr0YsQ73+Dzr74uRlYB0nmB0tSfAw="
}

resource "metabase_permissions_group" "example" {
  name = "example"
}
```

I tested against a fresh local instance of metabase from the official docker container.

**Comment by flovouin** [comment]
The API endpoint should be suffixed with `/api` like so:

```terraform
provider "metabase" {
  endpoint = "http://127.0.0.1:3000/api"
}
```

I'm not sure why this ends with a segfault rather than a readable message, I'll look into it.
